baseURL = "https://packtory.github.io/"
languageCode = "en-us"
title = "Packtory"
theme = "simplicity"

disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2018 Gemfury"

# Copied from simplicity: exampleSite/config.toml
defaultContentLanguage = "en"
disqusShortname = "test"
enableEmoji = true
enableRobotsTXT = true
pygmentsCodeFences = true
pygmentsStyle = "native"
pygmentsUseClasses =  true
[author]
  gravatarEmail = "test@example.com"
  homepageText = "Gemfury"
  name = "Gemfury"
  rss = "/posts/index.xml"
[imaging]
  anchor = "smart"
  resampleFilter = "box"
  quality = 75
[[menu.pages]]
  name = "Projects"
  weight = -100
  identifier = "projects"
  url = "/projects/"
[[menu.pages]]
  name = "Photos"
  weight = -90
  identifier = "photos"
  url = "/photos/"
[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
[params]
  adsenseClient = ''
  adsenseSlot = ''
  description = "Tool for building Ruby gems into system packages."
  licence = ""
  displayPostLanguage = true
[permalinks]
  posts = "/:year/:month/:day/:slug/"
[pygmentsOptions]
  linenos = false
